services:
  zoo:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    volumes:
      - zoo:/var/lib/zookeeper/data
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://tochkaszapyatoi.ru:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo
    volumes:
      - kafka:/var/lib/kafka/data
    networks:
      - backend

  notifypoint_db:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=notifypoint_db'
      - 'POSTGRES_PASSWORD=notifypoint_password'
      - 'POSTGRES_USER=notifypoint_user'
    ports:
      - "25432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/
    networks:
      - backend

  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - notifypoint_db
    networks:
      - backend

volumes:
  zoo: { }
  kafka: { }
  postgresql: { }

networks:
  backend:
    driver: bridge
