server:
  port: 8082

spring:
  application:
    name: notifypoint
  mail:
    host: smtp.yandex.ru
    port: 465
    username: "porseva.tatiana@yandex.ru"
    password: "obgdvkuhnvafsbfi"
    ssl:
      enabled: true
  datasource:
    url: jdbc:postgresql://notifypoint_db:5432/notifypoint_db
    username: notifypoint_user
    password: notifypoint_password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

management:
  endpoint:
    health:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include:
          - health
  server:
    port: 8082

kafka:
  consumers-enabled: true
  topics:
    notification:
      destination: notifypoint.notifications
      groupId: notifypoint.notifications.1
  clusters:
    default:
      bootstrap-servers:
        - kafka:9092
      properties:
        acks: -1
        delivery.timeout.ms: 90000
        batch.size: 10240
        linger.ms: 100
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
      consumer:
        client-id: tanpii.notifypoint
        group-id: tanpii.notifypoint
        enable-auto-commit: false
      listener:
        concurrency: 1
        ack-mode: record
      security:
        protocol: PLAINTEXT
